### ISSUE TITLE
Recompile for arm64e?

### ISSUE THREAD

**Issue by JEmlay** [angelXwind/AppSync#42] opened 2019-05-01 18:21 UTC
Leaving this here to keep an eye out on an arm64e version.  Hopefully no issues with Chimera.

It installed fine as is but of course it's not working.  iPad Pro Gen3

**Comment by JEmlay** [comment] 2019-05-13 17:03
Any love for A12 and A12X?

**Comment by JEmlay** [comment] 2019-05-28 15:54
Thanks for the update!  Unfortunately nothing will install properly. With the last version of ASU everything would go through the normal steps but then no app would exist on the system. Now when trying to install with iFunBox I get - "ERR: Package installation failed (-402620388)" (seems to be a code signing error) and when I try to install with Filza it wont even start the install steps. I get a spinning wheel then it just gives up.

iPad Pro Gen 3 (A12X)

**Comment by angelXwind** [comment] 2019-10-23 06:16
Issue lied with Substitute and not with ASU, and was fixed on unc0ver devices. Version 48.0 now has full support for A12/arm64e on unc0ver (Chimera support will be added once their Substitute version is updated).

**Closed by angelXwind** 2019-10-23 06:16 UTC

**Comment by JEmlay** [comment] 2019-10-25 16:49
That's good to hear.  Pretty crummy all that time had to be wasted though.  Today Substitute was update to v0.1.1 (says - Fixes an issue with certain functions failing to hook on A12).  Would it be a matter of just installing ASU and seeing if it works?  I don't want to blow up my jailbreak so I'm too chicken to try  ;p

**Comment by angelXwind** [comment] 2019-10-27 07:32
The issue is now fixed on the latest versions of Substitute found on both the unc0ver and Chimera jailbreaks. As long as you're using the correct version, all should be fine.

**Comment by JEmlay** [comment] 2019-10-27 14:38
Awesome, thank you!
